In [17]:
#모듈 불러오기
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [20]:
#데이터 불러오기
df_wine = pd.read_csv("../data/winequality-red.csv")
df_wine_test = pd.read_csv("../data/winequality-red_test.csv")
df_wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [14]:
#공백 데이터 여부 체크
df_wine.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [15]:
#예측하고자 하는 변수를 Y값으로, 학습 대상의 변수를 X값으로
x = df_wine.drop("quality", axis=1).values
y = df_wine["quality"].values

In [18]:
#표준화
scaler = StandardScaler()
x = scaler.fit_transform(x)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [19]:
#모델링
linear = LinearRegression()
linear.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [21]:
df_wine_test.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.3,0.670,0.02,2.20,0.072,31,92,0.99566,3.32,0.68,11.066667
1,7.2,0.370,0.32,2.00,0.062,15,28,0.99470,3.23,0.73,11.300000
2,7.4,0.785,0.19,5.20,0.094,19,98,0.99713,3.16,0.52,9.566667
3,6.9,0.630,0.02,1.90,0.078,18,30,0.99712,3.40,0.75,9.800000
4,6.9,0.580,0.20,1.75,0.058,8,22,0.99322,3.38,0.49,11.700000

In [22]:
x_text = df_wine_test.values

In [26]:
pred = linear.predict(x_test)
pred

array([6.37412394, 5.3280988 , 5.00731291, 5.71063679, 5.41153692,
       5.19788926, 6.30370001, 5.21688785, 5.51676975, 6.13223173,
       5.47245014, 6.65611741, 5.14185161, 6.63136541, 5.18162364,
       5.11662849, 5.17952843, 6.10690824, 5.06916448, 5.20652803,
       5.9119498 , 5.61115158, 6.44379904, 6.04832812, 5.43205447,
       6.20935988, 4.72136043, 5.09009291, 5.03211074, 6.07311802,
       6.48593701, 5.44073635, 6.10622859, 5.34588116, 5.49062453,
       5.14817095, 5.04157896, 5.09217937, 4.85409605, 6.38880479,
       5.38424231, 5.39857039, 5.35957778, 5.20984168, 5.12806808,
       6.13254615, 6.03882338, 5.10742111, 6.34937583, 5.52666624,
       5.78746375, 6.60262461, 6.56780386, 5.1610747 , 6.34211605,
       5.46184245, 5.73501016, 5.28825571, 5.12067757, 6.57129466,
       5.17214492, 5.7851006 , 6.54232427, 5.35873561, 5.74183684,
       5.55540925, 6.43724853, 5.91882001, 5.50384658, 5.28021834,
       5.18336074, 6.15279598, 5.7026578 , 6.32013039, 5.70839931,
       5.64667943, 5.46250185, 5.37166782, 5.1417033 , 5.12952671,
       6.37865996, 6.2185563 , 5.7042003 , 5.38229911, 5.06376625,
       6.13287764, 5.60297171, 5.44314589, 5.62931861, 5.82411819,
       5.1344386 , 4.97926243, 6.05348837, 4.80031039, 6.1185179 ,
       5.32779844, 5.6678751 , 5.00608945, 5.41334685, 6.37865996,
       6.15340624, 5.71544638, 6.62924871, 6.06453442, 5.71523832,
       6.11757672, 5.42881667, 5.64954766, 6.46482191, 5.73036632,
       5.45132657, 5.32709791, 5.2448737 , 6.78283007, 5.68932792,
       6.41606245, 5.90419973, 6.25115663, 5.30958039, 6.56266177,
       6.3801505 , 5.9305737 , 5.56216459, 5.40724276, 5.46440243,
       5.10705951, 5.31069055, 5.15798823, 5.99132256, 4.93324572,
       5.3876679 , 5.48606923, 5.50920691, 5.43260841, 5.47194355,
       5.47204633, 5.77325524, 6.52083205, 5.24669134, 6.13101259,
       5.3332062 , 6.4615597 , 5.7042003 , 5.31898389, 6.49243578,
       6.5145583 , 5.4518196 , 5.63769249, 5.97885181, 5.98977009,
       6.05736633, 5.73123189, 5.29908339, 5.19776679, 5.47087404,
       5.36143664, 6.24037743, 5.07923779, 6.24037743, 5.23339896,
       5.03026214, 5.40178991, 5.09242789, 5.2521738 , 6.21248709,
       5.08406111, 6.03526079, 5.1723012 , 6.26234333, 5.89257273,
       5.1301017 , 5.69733681, 6.10619899, 5.49170379, 6.50541423,
       5.47640592, 6.09240889, 5.61392356, 5.72262481, 5.4728308 ,
       6.28261063, 5.63368707, 6.25007181, 5.62757222, 6.06343884,
       5.82447977, 5.63207904, 6.21523972, 5.82052842, 5.71031169,
       6.07358795, 6.15340624, 5.24045231, 5.08474865, 5.97775053,
       5.04743594, 5.375828  , 5.13094294, 5.16575636, 5.72053116,
       6.81287152, 6.0014132 , 6.29184781, 6.50027691, 5.43072236,
       6.01919682, 6.41602658, 5.63185217, 6.45455373, 5.64686059,
       5.77060163, 5.64956951, 6.4157462 , 5.99132256, 5.36801076,
       6.19910034, 4.75697773, 6.66940542, 5.07751417, 5.00311265,
       5.97700519, 5.36443979, 5.69857   , 5.67378309, 5.50824468,
       5.7343356 , 5.21602278, 6.04637603, 5.74351936, 5.09005907,
       5.69930346, 5.6405019 , 4.82694878, 5.40111218, 5.52867226,
       5.24177425, 5.55866055, 6.15941743, 6.2230052 , 6.02691298,
       4.98817302, 5.06593178, 6.1011203 , 6.01919682, 6.35550972,
       4.95892955, 5.52363577, 5.47643866, 4.62496324, 5.73661858,
       6.61565754, 5.70025556, 6.41735595, 4.84883519, 5.64022614,
       5.37899275, 5.90465607, 5.2980917 , 5.82417959, 5.21799362,
       5.02376729, 5.77710278, 5.38631585, 6.32405145, 6.55551763,
       5.25498029, 5.07594842, 6.08412999, 5.45388192, 4.99853064,
       6.3419969 , 6.76850452, 5.72683975, 5.66919023, 5.12574791,
       5.48985491, 5.60145322, 5.56788789, 5.33827349, 5.41911891,
       5.18740056, 5.52533861, 5.35389141, 5.84565742, 5.36894937,
       5.30155183, 5.54025228, 6.3848234 ])

In [27]:
submission = pd.DataFrame(data=pred)
submission.to_csv("submission.csv")